version: '3.8'

services:
 notes:
  image: registry.hub.docker.com/library/node:18-alpine
  build:
   context: .
  ports:
   - 8000:8000
   - 9229:9229
  environment:
   - SERVER_PORT=8000
   - CONNECTIONSTRING=mongodb://mongo:27017/notes
  volumes:
   - ./:/app
   - /app/node_modules
  command: npm run debug

 mongo:
  image: registry.hub.docker.com/library/mongo:4.2.8
  ports:
   - 27017:27017
  volumes:
   - mongodb:/data/db
   - mongodb-config:/data/configdb
volumes:
 mongodb:
   driver: azure_file
   driver_opts:
      share_name: myacifileshare
      storage_account_name: myacistorageaccount
 mongodb-config:
   driver: azure_file
   driver_opts:
      share_name: myacifileshare
      storage_account_name: myacistorageaccount